version: '3.8'

services:
  wabase-bot:
    build: .
    container_name: wabase-bot
    restart: unless-stopped

    # Environment variables
    environment:
      - NODE_ENV=production
      - TZ=Asia/Jakarta

    # Mount environment file
    env_file:
      - .env

    # Volumes untuk data persistent
    volumes:
      - ./sezz:/app/sezz
      - ./database:/app/database
      - ./uploads:/app/uploads
      - ./logs:/app/logs

    # Network (opsional)
    networks:
      - wabase-network

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # Resource limits (opsional)
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  wabase-network:
    driver: bridge
